Search.appendIndex(
    [
                {
            "fqsen": "\\Actualitzar",
            "name": "Actualitzar",
            "summary": "",
            "url": "classes/Actualitzar.html"
        },                {
            "fqsen": "\\Actualitzar\u003A\u003Aactualizar\u0028\u0029",
            "name": "actualizar",
            "summary": "",
            "url": "classes/Actualitzar.html#method_actualizar"
        },                {
            "fqsen": "\\Connexio",
            "name": "Connexio",
            "summary": "",
            "url": "classes/Connexio.html"
        },                {
            "fqsen": "\\Connexio\u003A\u003AobtenirConnexio\u0028\u0029",
            "name": "obtenirConnexio",
            "summary": "",
            "url": "classes/Connexio.html#method_obtenirConnexio"
        },                {
            "fqsen": "\\Connexio\u003A\u003A\u0024host",
            "name": "host",
            "summary": "",
            "url": "classes/Connexio.html#property_host"
        },                {
            "fqsen": "\\Connexio\u003A\u003A\u0024usuario",
            "name": "usuario",
            "summary": "",
            "url": "classes/Connexio.html#property_usuario"
        },                {
            "fqsen": "\\Connexio\u003A\u003A\u0024contrase\u00F1a",
            "name": "contrase\u00F1a",
            "summary": "",
            "url": "classes/Connexio.html#property_contrase%C3%B1a"
        },                {
            "fqsen": "\\Connexio\u003A\u003A\u0024baseDatos",
            "name": "baseDatos",
            "summary": "",
            "url": "classes/Connexio.html#property_baseDatos"
        },                {
            "fqsen": "\\Eliminar",
            "name": "Eliminar",
            "summary": "La\u0020classe\u0020Eliminar\u0020representa\u0020l\u2019eliminaci\u00F3\u0020de\u0020productes\u0020en\u0020la\u0020BBDD",
            "url": "classes/Eliminar.html"
        },                {
            "fqsen": "\\Eliminar\u003A\u003AconfirmarEliminacio\u0028\u0029",
            "name": "confirmarEliminacio",
            "summary": "El\u0020m\u00E8tode\u0020confirmarEliminacio\u0028\u0024id\u0029\u0020comprova\u0020l\u2019exist\u00E8ncia\ndel\u0020producte\u0020i\u0020demana\u0020confirmaci\u00F3\u0020a\u0020l\u2019usuari",
            "url": "classes/Eliminar.html#method_confirmarEliminacio"
        },                {
            "fqsen": "\\Eliminar\u003A\u003AprocesarEliminacion\u0028\u0029",
            "name": "procesarEliminacion",
            "summary": "El\u0020m\u00E8tode\u0020procesarEliminacio\u0028\u0024id\u0029\u0020executa\u0020la\u0020consulta\nd\u2019eliminaci\u00F3\u0020del\u0020producte",
            "url": "classes/Eliminar.html#method_procesarEliminacion"
        },                {
            "fqsen": "\\Footer",
            "name": "Footer",
            "summary": "",
            "url": "classes/Footer.html"
        },                {
            "fqsen": "\\Footer\u003A\u003AmostrarFooter\u0028\u0029",
            "name": "mostrarFooter",
            "summary": "",
            "url": "classes/Footer.html#method_mostrarFooter"
        },                {
            "fqsen": "\\Header",
            "name": "Header",
            "summary": "",
            "url": "classes/Header.html"
        },                {
            "fqsen": "\\Header\u003A\u003AmostrarHeader\u0028\u0029",
            "name": "mostrarHeader",
            "summary": "",
            "url": "classes/Header.html#method_mostrarHeader"
        },                {
            "fqsen": "\\Modificar",
            "name": "Modificar",
            "summary": "",
            "url": "classes/Modificar.html"
        },                {
            "fqsen": "\\Modificar\u003A\u003AmostrarFormulari\u0028\u0029",
            "name": "mostrarFormulari",
            "summary": "",
            "url": "classes/Modificar.html#method_mostrarFormulari"
        },                {
            "fqsen": "\\Afegir",
            "name": "Afegir",
            "summary": "La\u0020classe\u0020Afegir\u0020representa\u0020la\u0020inserci\u00F3\u0020de\u0020nous\u0020productes\u0020en\u0020la\u0020BBDD",
            "url": "classes/Afegir.html"
        },                {
            "fqsen": "\\Afegir\u003A\u003AmostrarFormulari\u0028\u0029",
            "name": "mostrarFormulari",
            "summary": "El\u0020m\u00E8tode\u0020mostrarFormulari\u0028\u0029\u0020genera\u0020el\u0020codi\u0020HTML\u0020del\u0020formulari\nper\u0020inserir\u0020un\u0020nou\u0020producte\u0020en\u0020la\u0020taula\u0020productes",
            "url": "classes/Afegir.html#method_mostrarFormulari"
        },                {
            "fqsen": "\\Principal",
            "name": "Principal",
            "summary": "",
            "url": "classes/Principal.html"
        },                {
            "fqsen": "\\Principal\u003A\u003AmostrarProductes\u0028\u0029",
            "name": "mostrarProductes",
            "summary": "",
            "url": "classes/Principal.html#method_mostrarProductes"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
